<footer>
        <section id="left">
          <h4>Contact us via phone or email:</h4>
          <p>Phone: 1-800-123-4567<br>
             Email: support@aerostar.com
          </p>
        </section>
        <section id="middle">
          <h4> &copy; AeroStar - All Rights Reserved.</h4>
        </section>
        <section id="right">
          <h4>Connect with us:</h4>
          <a href="https://www.facebook.com/airasia/" target="_blank"><img src="images/facebook.png" alt="Facebook"></a>
          <a href="https://www.instagram.com/airasiasuperapp/" target="_blank"><img src="images/instagram.png" alt="Instagram"></a>
          <a href="https://twitter.com/airasia" target="_blank"><img src="images/twitter.png" alt="Twitter"></a>
        </section>
        <section id="bottom">
        <h4>Privacy Policy</h4>
        <p>We respect your privacy and are committed to protecting your personal information. We may collect information such as 
        your name, email address, and IP address when you visit our website. This information is used to improve our website 
        and to communicate with you about our products and services. We do not share your information with third parties, 
        except as necessary to provide our products and services or as required by law.
        </p>
      </section>
</footer>