<header>
        <div id="top"></div>
        <section class="logo-container">
          <img src="images/AeroStarLogo.png" alt="AeroStar Logo">
          <h1>AeroStar - Taking you higher</h1>
        </section>
        <nav>
          <ul>
            <li><a href="manager.php">Manager Page</a></li>
            <li><a href="manager_registration.php">Manager Registration</a></li>
          </ul>
        </nav>
        <a href="manager_logout.php"><button>Logout</button></a><br>
</header>