<nav>
    <ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="product.php">Flights</a></li>
    <li><a href="enquire.php">Enquire</a></li>
    <li><a href="about.php">About</a></li>
    <li class="dropdown">
        <a>Manager</a>
        <ul class="dropdown-menu">
        <li><a href="manager.php">Manager Page</a></li>
        <li><a href="manager_login.php">Manager Login</a></li>
        <li><a href="manager_registration.php">Manager Registration</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a>Enhancements</a>
        <ul class="dropdown-menu">
        <li><a href="enhancements.php">Enhancements</a></li>
        <li><a href="enhancements2.php">Enhancements 2</a></li>
        <li><a href="enhancements3.php">Enhancements 3</a></li>
        </ul>
    </li>
    </ul>
</nav>